// This file was auto-generated by ML.NET Model Builder. 

using System;
using EchoBot1ML.Model;

namespace EchoBot1ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Prompt = @"I remember going to the fireworks with my best friend. There was a lot of people_comma_ but it only felt like us in the world.",
                Utterance = @"I remember going to see the fireworks with my best friend. It was the first time we ever spent time alone together. Although there was a lot of people_comma_ we felt like the only people in the world.",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Context with predicted Context from sample data...\n\n");
            Console.WriteLine($"Prompt: {sampleData.Prompt}");
            Console.WriteLine($"Utterance: {sampleData.Utterance}");
            Console.WriteLine($"\n\nPredicted Context value {predictionResult.Prediction} \nPredicted Context scores: [{String.Join(",", predictionResult.Score)}]\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
