// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace EchoBot1ML.Model
{
    public class ModelInput
    {
        [ColumnName("conv_id"), LoadColumn(0)]
        public string Conv_id { get; set; }


        [ColumnName("utterance_idx"), LoadColumn(1)]
        public float Utterance_idx { get; set; }


        [ColumnName("context"), LoadColumn(2)]
        public string Context { get; set; }


        [ColumnName("prompt"), LoadColumn(3)]
        public string Prompt { get; set; }


        [ColumnName("speaker_idx"), LoadColumn(4)]
        public float Speaker_idx { get; set; }


        [ColumnName("utterance"), LoadColumn(5)]
        public string Utterance { get; set; }


        [ColumnName("selfeval"), LoadColumn(6)]
        public string Selfeval { get; set; }


        [ColumnName("tags"), LoadColumn(7)]
        public string Tags { get; set; }


    }
}
